name: Run Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Dependencies
      run: |
        pip install python-telegram-bot
        pip install requests
    
    - name: Run Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        SERVER_TOKEN: ${{ secrets.SERVER_TOKEN }}  # Ganti GITHUB_TOKEN jadi SERVER_TOKEN
      run: python bot.py
